apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    service: dummy
spec:
  selector:
    matchLabels:
      service: dummy
  template:
    metadata:
      labels:
        service: dummy
    spec:
      containers:
      - name: nginx
        image: gcr.io/pf-msa-labo/hilenet-nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
      - name: sidecar
        image: redis
